// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/com/bankledger/protobuf/spos.proto

package org.bitcoin.safe;

public final class SposProtos {
  private SposProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DeterministicMasternodeDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bankledger.safegem.DeterministicMasternodeData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes ip = 1;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    boolean hasIp();
    /**
     * <code>required bytes ip = 1;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    com.google.protobuf.ByteString getIp();

    /**
     * <code>required bytes port = 2;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    boolean hasPort();
    /**
     * <code>required bytes port = 2;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    com.google.protobuf.ByteString getPort();

    /**
     * <code>required bytes collateralAddress = 3;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    boolean hasCollateralAddress();
    /**
     * <code>required bytes collateralAddress = 3;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    com.google.protobuf.ByteString getCollateralAddress();

    /**
     * <code>required bytes txid = 4;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    boolean hasTxid();
    /**
     * <code>required bytes txid = 4;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    com.google.protobuf.ByteString getTxid();

    /**
     * <code>required bytes outputIndex = 5;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    boolean hasOutputIndex();
    /**
     * <code>required bytes outputIndex = 5;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    com.google.protobuf.ByteString getOutputIndex();

    /**
     * <code>required bytes serialPubkeyId = 6;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    boolean hasSerialPubkeyId();
    /**
     * <code>required bytes serialPubkeyId = 6;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    com.google.protobuf.ByteString getSerialPubkeyId();

    /**
     * <code>required bytes signedMsg = 7;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    boolean hasSignedMsg();
    /**
     * <code>required bytes signedMsg = 7;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    com.google.protobuf.ByteString getSignedMsg();

    /**
     * <code>required bytes officialSignedMsg = 8;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    boolean hasOfficialSignedMsg();
    /**
     * <code>required bytes officialSignedMsg = 8;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    com.google.protobuf.ByteString getOfficialSignedMsg();
  }
  /**
   * Protobuf type {@code com.bankledger.safegem.DeterministicMasternodeData}
   */
  public static final class DeterministicMasternodeData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.bankledger.safegem.DeterministicMasternodeData)
      DeterministicMasternodeDataOrBuilder {
    // Use DeterministicMasternodeData.newBuilder() to construct.
    private DeterministicMasternodeData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DeterministicMasternodeData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DeterministicMasternodeData defaultInstance;
    public static DeterministicMasternodeData getDefaultInstance() {
      return defaultInstance;
    }

    public DeterministicMasternodeData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DeterministicMasternodeData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              ip_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              port_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              collateralAddress_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              txid_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              outputIndex_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              serialPubkeyId_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              signedMsg_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              officialSignedMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SposProtos.internal_static_com_bankledger_safegem_DeterministicMasternodeData_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SposProtos.internal_static_com_bankledger_safegem_DeterministicMasternodeData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DeterministicMasternodeData.class, Builder.class);
    }

    public static com.google.protobuf.Parser<DeterministicMasternodeData> PARSER =
        new com.google.protobuf.AbstractParser<DeterministicMasternodeData>() {
      public DeterministicMasternodeData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeterministicMasternodeData(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<DeterministicMasternodeData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int IP_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString ip_;
    /**
     * <code>required bytes ip = 1;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes ip = 1;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    public com.google.protobuf.ByteString getIp() {
      return ip_;
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString port_;
    /**
     * <code>required bytes port = 2;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes port = 2;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    public com.google.protobuf.ByteString getPort() {
      return port_;
    }

    public static final int COLLATERALADDRESS_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString collateralAddress_;
    /**
     * <code>required bytes collateralAddress = 3;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    public boolean hasCollateralAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes collateralAddress = 3;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    public com.google.protobuf.ByteString getCollateralAddress() {
      return collateralAddress_;
    }

    public static final int TXID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString txid_;
    /**
     * <code>required bytes txid = 4;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    public boolean hasTxid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes txid = 4;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    public com.google.protobuf.ByteString getTxid() {
      return txid_;
    }

    public static final int OUTPUTINDEX_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString outputIndex_;
    /**
     * <code>required bytes outputIndex = 5;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    public boolean hasOutputIndex() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bytes outputIndex = 5;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    public com.google.protobuf.ByteString getOutputIndex() {
      return outputIndex_;
    }

    public static final int SERIALPUBKEYID_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString serialPubkeyId_;
    /**
     * <code>required bytes serialPubkeyId = 6;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    public boolean hasSerialPubkeyId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bytes serialPubkeyId = 6;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    public com.google.protobuf.ByteString getSerialPubkeyId() {
      return serialPubkeyId_;
    }

    public static final int SIGNEDMSG_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString signedMsg_;
    /**
     * <code>required bytes signedMsg = 7;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    public boolean hasSignedMsg() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required bytes signedMsg = 7;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    public com.google.protobuf.ByteString getSignedMsg() {
      return signedMsg_;
    }

    public static final int OFFICIALSIGNEDMSG_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString officialSignedMsg_;
    /**
     * <code>required bytes officialSignedMsg = 8;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    public boolean hasOfficialSignedMsg() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required bytes officialSignedMsg = 8;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    public com.google.protobuf.ByteString getOfficialSignedMsg() {
      return officialSignedMsg_;
    }

    private void initFields() {
      ip_ = com.google.protobuf.ByteString.EMPTY;
      port_ = com.google.protobuf.ByteString.EMPTY;
      collateralAddress_ = com.google.protobuf.ByteString.EMPTY;
      txid_ = com.google.protobuf.ByteString.EMPTY;
      outputIndex_ = com.google.protobuf.ByteString.EMPTY;
      serialPubkeyId_ = com.google.protobuf.ByteString.EMPTY;
      signedMsg_ = com.google.protobuf.ByteString.EMPTY;
      officialSignedMsg_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCollateralAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTxid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOutputIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSerialPubkeyId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSignedMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOfficialSignedMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, ip_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, collateralAddress_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, txid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, outputIndex_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, serialPubkeyId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, signedMsg_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, officialSignedMsg_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, ip_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, collateralAddress_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, txid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, outputIndex_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, serialPubkeyId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, signedMsg_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, officialSignedMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DeterministicMasternodeData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeterministicMasternodeData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeterministicMasternodeData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeterministicMasternodeData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeterministicMasternodeData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DeterministicMasternodeData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DeterministicMasternodeData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DeterministicMasternodeData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DeterministicMasternodeData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DeterministicMasternodeData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DeterministicMasternodeData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bankledger.safegem.DeterministicMasternodeData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bankledger.safegem.DeterministicMasternodeData)
        DeterministicMasternodeDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SposProtos.internal_static_com_bankledger_safegem_DeterministicMasternodeData_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SposProtos.internal_static_com_bankledger_safegem_DeterministicMasternodeData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DeterministicMasternodeData.class, Builder.class);
      }

      // Construct using org.bitcoin.safe.SposProtos.DeterministicMasternodeData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ip_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        collateralAddress_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        txid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        outputIndex_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        serialPubkeyId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        signedMsg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        officialSignedMsg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SposProtos.internal_static_com_bankledger_safegem_DeterministicMasternodeData_descriptor;
      }

      public DeterministicMasternodeData getDefaultInstanceForType() {
        return DeterministicMasternodeData.getDefaultInstance();
      }

      public DeterministicMasternodeData build() {
        DeterministicMasternodeData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DeterministicMasternodeData buildPartial() {
        DeterministicMasternodeData result = new DeterministicMasternodeData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.collateralAddress_ = collateralAddress_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.txid_ = txid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.outputIndex_ = outputIndex_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.serialPubkeyId_ = serialPubkeyId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.signedMsg_ = signedMsg_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.officialSignedMsg_ = officialSignedMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DeterministicMasternodeData) {
          return mergeFrom((DeterministicMasternodeData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DeterministicMasternodeData other) {
        if (other == DeterministicMasternodeData.getDefaultInstance()) return this;
        if (other.hasIp()) {
          setIp(other.getIp());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasCollateralAddress()) {
          setCollateralAddress(other.getCollateralAddress());
        }
        if (other.hasTxid()) {
          setTxid(other.getTxid());
        }
        if (other.hasOutputIndex()) {
          setOutputIndex(other.getOutputIndex());
        }
        if (other.hasSerialPubkeyId()) {
          setSerialPubkeyId(other.getSerialPubkeyId());
        }
        if (other.hasSignedMsg()) {
          setSignedMsg(other.getSignedMsg());
        }
        if (other.hasOfficialSignedMsg()) {
          setOfficialSignedMsg(other.getOfficialSignedMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIp()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        if (!hasCollateralAddress()) {
          
          return false;
        }
        if (!hasTxid()) {
          
          return false;
        }
        if (!hasOutputIndex()) {
          
          return false;
        }
        if (!hasSerialPubkeyId()) {
          
          return false;
        }
        if (!hasSignedMsg()) {
          
          return false;
        }
        if (!hasOfficialSignedMsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DeterministicMasternodeData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DeterministicMasternodeData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString ip_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes ip = 1;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes ip = 1;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public com.google.protobuf.ByteString getIp() {
        return ip_;
      }
      /**
       * <code>required bytes ip = 1;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public Builder setIp(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes ip = 1;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString port_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes port = 2;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes port = 2;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public com.google.protobuf.ByteString getPort() {
        return port_;
      }
      /**
       * <code>required bytes port = 2;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public Builder setPort(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes port = 2;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = getDefaultInstance().getPort();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString collateralAddress_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes collateralAddress = 3;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public boolean hasCollateralAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes collateralAddress = 3;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public com.google.protobuf.ByteString getCollateralAddress() {
        return collateralAddress_;
      }
      /**
       * <code>required bytes collateralAddress = 3;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public Builder setCollateralAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        collateralAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes collateralAddress = 3;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public Builder clearCollateralAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        collateralAddress_ = getDefaultInstance().getCollateralAddress();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString txid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes txid = 4;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public boolean hasTxid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes txid = 4;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public com.google.protobuf.ByteString getTxid() {
        return txid_;
      }
      /**
       * <code>required bytes txid = 4;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public Builder setTxid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        txid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes txid = 4;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public Builder clearTxid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        txid_ = getDefaultInstance().getTxid();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString outputIndex_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes outputIndex = 5;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public boolean hasOutputIndex() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bytes outputIndex = 5;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public com.google.protobuf.ByteString getOutputIndex() {
        return outputIndex_;
      }
      /**
       * <code>required bytes outputIndex = 5;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public Builder setOutputIndex(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        outputIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes outputIndex = 5;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public Builder clearOutputIndex() {
        bitField0_ = (bitField0_ & ~0x00000010);
        outputIndex_ = getDefaultInstance().getOutputIndex();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString serialPubkeyId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes serialPubkeyId = 6;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public boolean hasSerialPubkeyId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bytes serialPubkeyId = 6;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public com.google.protobuf.ByteString getSerialPubkeyId() {
        return serialPubkeyId_;
      }
      /**
       * <code>required bytes serialPubkeyId = 6;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public Builder setSerialPubkeyId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        serialPubkeyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes serialPubkeyId = 6;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public Builder clearSerialPubkeyId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        serialPubkeyId_ = getDefaultInstance().getSerialPubkeyId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signedMsg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes signedMsg = 7;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public boolean hasSignedMsg() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required bytes signedMsg = 7;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public com.google.protobuf.ByteString getSignedMsg() {
        return signedMsg_;
      }
      /**
       * <code>required bytes signedMsg = 7;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public Builder setSignedMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        signedMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes signedMsg = 7;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public Builder clearSignedMsg() {
        bitField0_ = (bitField0_ & ~0x00000040);
        signedMsg_ = getDefaultInstance().getSignedMsg();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString officialSignedMsg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes officialSignedMsg = 8;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public boolean hasOfficialSignedMsg() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required bytes officialSignedMsg = 8;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public com.google.protobuf.ByteString getOfficialSignedMsg() {
        return officialSignedMsg_;
      }
      /**
       * <code>required bytes officialSignedMsg = 8;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public Builder setOfficialSignedMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        officialSignedMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes officialSignedMsg = 8;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public Builder clearOfficialSignedMsg() {
        bitField0_ = (bitField0_ & ~0x00000080);
        officialSignedMsg_ = getDefaultInstance().getOfficialSignedMsg();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.bankledger.safegem.DeterministicMasternodeData)
    }

    static {
      defaultInstance = new DeterministicMasternodeData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.bankledger.safegem.DeterministicMasternodeData)
  }

  public interface DeterministicCoinbaseDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bankledger.safegem.DeterministicCoinbaseData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes pubkeyId = 1;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    boolean hasPubkeyId();
    /**
     * <code>required bytes pubkeyId = 1;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    com.google.protobuf.ByteString getPubkeyId();

    /**
     * <code>required bytes officialMNNum = 2;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    boolean hasOfficialMNNum();
    /**
     * <code>required bytes officialMNNum = 2;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    com.google.protobuf.ByteString getOfficialMNNum();

    /**
     * <code>required bytes generalMNNum = 3;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    boolean hasGeneralMNNum();
    /**
     * <code>required bytes generalMNNum = 3;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    com.google.protobuf.ByteString getGeneralMNNum();

    /**
     * <code>required bytes randomNum = 4;</code>
     *
     * <pre>
     * uint32_t
     * </pre>
     */
    boolean hasRandomNum();
    /**
     * <code>required bytes randomNum = 4;</code>
     *
     * <pre>
     * uint32_t
     * </pre>
     */
    com.google.protobuf.ByteString getRandomNum();

    /**
     * <code>required bytes firstBlock = 5;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    boolean hasFirstBlock();
    /**
     * <code>required bytes firstBlock = 5;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    com.google.protobuf.ByteString getFirstBlock();

    /**
     * <code>required bytes signMsg = 6;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    boolean hasSignMsg();
    /**
     * <code>required bytes signMsg = 6;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    com.google.protobuf.ByteString getSignMsg();
  }
  /**
   * Protobuf type {@code com.bankledger.safegem.DeterministicCoinbaseData}
   */
  public static final class DeterministicCoinbaseData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.bankledger.safegem.DeterministicCoinbaseData)
      DeterministicCoinbaseDataOrBuilder {
    // Use DeterministicCoinbaseData.newBuilder() to construct.
    private DeterministicCoinbaseData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DeterministicCoinbaseData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DeterministicCoinbaseData defaultInstance;
    public static DeterministicCoinbaseData getDefaultInstance() {
      return defaultInstance;
    }

    public DeterministicCoinbaseData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DeterministicCoinbaseData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              pubkeyId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              officialMNNum_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              generalMNNum_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              randomNum_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              firstBlock_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              signMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SposProtos.internal_static_com_bankledger_safegem_DeterministicCoinbaseData_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SposProtos.internal_static_com_bankledger_safegem_DeterministicCoinbaseData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DeterministicCoinbaseData.class, Builder.class);
    }

    public static com.google.protobuf.Parser<DeterministicCoinbaseData> PARSER =
        new com.google.protobuf.AbstractParser<DeterministicCoinbaseData>() {
      public DeterministicCoinbaseData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeterministicCoinbaseData(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<DeterministicCoinbaseData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PUBKEYID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString pubkeyId_;
    /**
     * <code>required bytes pubkeyId = 1;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    public boolean hasPubkeyId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes pubkeyId = 1;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    public com.google.protobuf.ByteString getPubkeyId() {
      return pubkeyId_;
    }

    public static final int OFFICIALMNNUM_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString officialMNNum_;
    /**
     * <code>required bytes officialMNNum = 2;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    public boolean hasOfficialMNNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes officialMNNum = 2;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    public com.google.protobuf.ByteString getOfficialMNNum() {
      return officialMNNum_;
    }

    public static final int GENERALMNNUM_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString generalMNNum_;
    /**
     * <code>required bytes generalMNNum = 3;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    public boolean hasGeneralMNNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes generalMNNum = 3;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    public com.google.protobuf.ByteString getGeneralMNNum() {
      return generalMNNum_;
    }

    public static final int RANDOMNUM_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString randomNum_;
    /**
     * <code>required bytes randomNum = 4;</code>
     *
     * <pre>
     * uint32_t
     * </pre>
     */
    public boolean hasRandomNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes randomNum = 4;</code>
     *
     * <pre>
     * uint32_t
     * </pre>
     */
    public com.google.protobuf.ByteString getRandomNum() {
      return randomNum_;
    }

    public static final int FIRSTBLOCK_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString firstBlock_;
    /**
     * <code>required bytes firstBlock = 5;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    public boolean hasFirstBlock() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bytes firstBlock = 5;</code>
     *
     * <pre>
     * uint16_t
     * </pre>
     */
    public com.google.protobuf.ByteString getFirstBlock() {
      return firstBlock_;
    }

    public static final int SIGNMSG_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString signMsg_;
    /**
     * <code>required bytes signMsg = 6;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    public boolean hasSignMsg() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bytes signMsg = 6;</code>
     *
     * <pre>
     * string
     * </pre>
     */
    public com.google.protobuf.ByteString getSignMsg() {
      return signMsg_;
    }

    private void initFields() {
      pubkeyId_ = com.google.protobuf.ByteString.EMPTY;
      officialMNNum_ = com.google.protobuf.ByteString.EMPTY;
      generalMNNum_ = com.google.protobuf.ByteString.EMPTY;
      randomNum_ = com.google.protobuf.ByteString.EMPTY;
      firstBlock_ = com.google.protobuf.ByteString.EMPTY;
      signMsg_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPubkeyId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOfficialMNNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGeneralMNNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRandomNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFirstBlock()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSignMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, pubkeyId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, officialMNNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, generalMNNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, randomNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, firstBlock_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, signMsg_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, pubkeyId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, officialMNNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, generalMNNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, randomNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, firstBlock_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, signMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DeterministicCoinbaseData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeterministicCoinbaseData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeterministicCoinbaseData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeterministicCoinbaseData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeterministicCoinbaseData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DeterministicCoinbaseData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DeterministicCoinbaseData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DeterministicCoinbaseData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DeterministicCoinbaseData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DeterministicCoinbaseData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DeterministicCoinbaseData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bankledger.safegem.DeterministicCoinbaseData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bankledger.safegem.DeterministicCoinbaseData)
        DeterministicCoinbaseDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SposProtos.internal_static_com_bankledger_safegem_DeterministicCoinbaseData_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SposProtos.internal_static_com_bankledger_safegem_DeterministicCoinbaseData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DeterministicCoinbaseData.class, Builder.class);
      }

      // Construct using org.bitcoin.safe.SposProtos.DeterministicCoinbaseData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        pubkeyId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        officialMNNum_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        generalMNNum_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        randomNum_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        firstBlock_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        signMsg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SposProtos.internal_static_com_bankledger_safegem_DeterministicCoinbaseData_descriptor;
      }

      public DeterministicCoinbaseData getDefaultInstanceForType() {
        return DeterministicCoinbaseData.getDefaultInstance();
      }

      public DeterministicCoinbaseData build() {
        DeterministicCoinbaseData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DeterministicCoinbaseData buildPartial() {
        DeterministicCoinbaseData result = new DeterministicCoinbaseData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pubkeyId_ = pubkeyId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.officialMNNum_ = officialMNNum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.generalMNNum_ = generalMNNum_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.randomNum_ = randomNum_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.firstBlock_ = firstBlock_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.signMsg_ = signMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DeterministicCoinbaseData) {
          return mergeFrom((DeterministicCoinbaseData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DeterministicCoinbaseData other) {
        if (other == DeterministicCoinbaseData.getDefaultInstance()) return this;
        if (other.hasPubkeyId()) {
          setPubkeyId(other.getPubkeyId());
        }
        if (other.hasOfficialMNNum()) {
          setOfficialMNNum(other.getOfficialMNNum());
        }
        if (other.hasGeneralMNNum()) {
          setGeneralMNNum(other.getGeneralMNNum());
        }
        if (other.hasRandomNum()) {
          setRandomNum(other.getRandomNum());
        }
        if (other.hasFirstBlock()) {
          setFirstBlock(other.getFirstBlock());
        }
        if (other.hasSignMsg()) {
          setSignMsg(other.getSignMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPubkeyId()) {
          
          return false;
        }
        if (!hasOfficialMNNum()) {
          
          return false;
        }
        if (!hasGeneralMNNum()) {
          
          return false;
        }
        if (!hasRandomNum()) {
          
          return false;
        }
        if (!hasFirstBlock()) {
          
          return false;
        }
        if (!hasSignMsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DeterministicCoinbaseData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DeterministicCoinbaseData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString pubkeyId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes pubkeyId = 1;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public boolean hasPubkeyId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes pubkeyId = 1;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public com.google.protobuf.ByteString getPubkeyId() {
        return pubkeyId_;
      }
      /**
       * <code>required bytes pubkeyId = 1;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public Builder setPubkeyId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pubkeyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes pubkeyId = 1;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public Builder clearPubkeyId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pubkeyId_ = getDefaultInstance().getPubkeyId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString officialMNNum_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes officialMNNum = 2;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public boolean hasOfficialMNNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes officialMNNum = 2;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public com.google.protobuf.ByteString getOfficialMNNum() {
        return officialMNNum_;
      }
      /**
       * <code>required bytes officialMNNum = 2;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public Builder setOfficialMNNum(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        officialMNNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes officialMNNum = 2;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public Builder clearOfficialMNNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        officialMNNum_ = getDefaultInstance().getOfficialMNNum();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString generalMNNum_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes generalMNNum = 3;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public boolean hasGeneralMNNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes generalMNNum = 3;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public com.google.protobuf.ByteString getGeneralMNNum() {
        return generalMNNum_;
      }
      /**
       * <code>required bytes generalMNNum = 3;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public Builder setGeneralMNNum(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        generalMNNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes generalMNNum = 3;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public Builder clearGeneralMNNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        generalMNNum_ = getDefaultInstance().getGeneralMNNum();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString randomNum_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes randomNum = 4;</code>
       *
       * <pre>
       * uint32_t
       * </pre>
       */
      public boolean hasRandomNum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes randomNum = 4;</code>
       *
       * <pre>
       * uint32_t
       * </pre>
       */
      public com.google.protobuf.ByteString getRandomNum() {
        return randomNum_;
      }
      /**
       * <code>required bytes randomNum = 4;</code>
       *
       * <pre>
       * uint32_t
       * </pre>
       */
      public Builder setRandomNum(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        randomNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes randomNum = 4;</code>
       *
       * <pre>
       * uint32_t
       * </pre>
       */
      public Builder clearRandomNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        randomNum_ = getDefaultInstance().getRandomNum();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString firstBlock_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes firstBlock = 5;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public boolean hasFirstBlock() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bytes firstBlock = 5;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public com.google.protobuf.ByteString getFirstBlock() {
        return firstBlock_;
      }
      /**
       * <code>required bytes firstBlock = 5;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public Builder setFirstBlock(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        firstBlock_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes firstBlock = 5;</code>
       *
       * <pre>
       * uint16_t
       * </pre>
       */
      public Builder clearFirstBlock() {
        bitField0_ = (bitField0_ & ~0x00000010);
        firstBlock_ = getDefaultInstance().getFirstBlock();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signMsg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes signMsg = 6;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public boolean hasSignMsg() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bytes signMsg = 6;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public com.google.protobuf.ByteString getSignMsg() {
        return signMsg_;
      }
      /**
       * <code>required bytes signMsg = 6;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public Builder setSignMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        signMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes signMsg = 6;</code>
       *
       * <pre>
       * string
       * </pre>
       */
      public Builder clearSignMsg() {
        bitField0_ = (bitField0_ & ~0x00000020);
        signMsg_ = getDefaultInstance().getSignMsg();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.bankledger.safegem.DeterministicCoinbaseData)
    }

    static {
      defaultInstance = new DeterministicCoinbaseData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.bankledger.safegem.DeterministicCoinbaseData)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bankledger_safegem_DeterministicMasternodeData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bankledger_safegem_DeterministicMasternodeData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bankledger_safegem_DeterministicCoinbaseData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bankledger_safegem_DeterministicCoinbaseData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n,main/java/com/bankledger/protobuf/spos" +
      ".proto\022\026com.bankledger.safegem\"\273\001\n\033Deter" +
      "ministicMasternodeData\022\n\n\002ip\030\001 \002(\014\022\014\n\004po" +
      "rt\030\002 \002(\014\022\031\n\021collateralAddress\030\003 \002(\014\022\014\n\004t" +
      "xid\030\004 \002(\014\022\023\n\013outputIndex\030\005 \002(\014\022\026\n\016serial" +
      "PubkeyId\030\006 \002(\014\022\021\n\tsignedMsg\030\007 \002(\014\022\031\n\021off" +
      "icialSignedMsg\030\010 \002(\014\"\222\001\n\031DeterministicCo" +
      "inbaseData\022\020\n\010pubkeyId\030\001 \002(\014\022\025\n\rofficial" +
      "MNNum\030\002 \002(\014\022\024\n\014generalMNNum\030\003 \002(\014\022\021\n\tran" +
      "domNum\030\004 \002(\014\022\022\n\nfirstBlock\030\005 \002(\014\022\017\n\007sign",
      "Msg\030\006 \002(\014B\036\n\020org.bitcoin.safeB\nSposProto" +
      "s"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_bankledger_safegem_DeterministicMasternodeData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bankledger_safegem_DeterministicMasternodeData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bankledger_safegem_DeterministicMasternodeData_descriptor,
        new String[] { "Ip", "Port", "CollateralAddress", "Txid", "OutputIndex", "SerialPubkeyId", "SignedMsg", "OfficialSignedMsg", });
    internal_static_com_bankledger_safegem_DeterministicCoinbaseData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bankledger_safegem_DeterministicCoinbaseData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bankledger_safegem_DeterministicCoinbaseData_descriptor,
        new String[] { "PubkeyId", "OfficialMNNum", "GeneralMNNum", "RandomNum", "FirstBlock", "SignMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)

}
